export const FETCHING_DATA = "FETCHING_DATA";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";

export const FILTERED_DATA_REQUEST = "FILTERED_DATA_REQUEST";
export const FILTERED_DATA_SUCCESS = "FILTERED_DATA_SUCCESS";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const FETCHING_ID_DATA = "FETCHING_ID_DATA";
export const FETCHING_ID_DATA_SUCCESS = "FETCHING_ID_DATA_SUCCESS";

export const CART_ITEM_DELETE = "CART_ITEM_DELETE";
